// Sample data for FlatList
const data = [
  {
    id: '1',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '2',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '3',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '4',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '5',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '6',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '7',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '8',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '9',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '10',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '11',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '12',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '13',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '14',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '15',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '16',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '17',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '18',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '19',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '20',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '21',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '22',
    name: 'उषा कश्यप / अजीत कुमार',
    sectionNumber: ' 1',
    gender: 'F',
    age: '79',
  },
  {
    id: '23',
    name: 'अजीत कुमार',
    sectionNumber: ' 2',
    gender: 'M',
    age: '84',
  },
  // Add more data as needed
];
export default data;
