// Sample data for FlatList
const data = [
  {
    id: '1',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '2',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '3',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '4',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '5',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '6',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '7',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '8',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '9',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '10',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '11',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '12',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '13',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '14',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '15',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '16',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '17',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '18',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '19',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '20',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '21',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '1',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '22',
    hindiName: 'उषा कश्यप / अजीत कुमार',
    englishName: 'usha kashyap / ajeet kumar',
    sectionNumber: '11',
    gender: 'F',
    age: '79',
    village: 'khajri',
    panchayat: 'khajri panchayat',
    area: 'boria',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '23',
    hindiName: 'सुशील कुमार / नेकराम',
    englishName: 'susheel kumar / nekram',
    sectionNumber: '2',
    gender: 'M',
    age: '84',
    village: 'pawai',
    panchayat: 'baddi panchayat',
    area: 'tarnam',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  {
    id: '24',
    hindiName: 'संदीप कुररिया / रामकिशोर कुररिया',
    englishName: 'sandeep kuraria / ramkishor kuraria',
    sectionNumber: '3',
    gender: 'M',
    age: '34',
    village: 'kankarkheda',
    panchayat: 'kankarkheda panchayat',
    area: '44 meal',
    jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  },
  // Add more data as needed
];
export default data;
