const hindiText = {
  jabalpurPaschimAssembly2024: 'विधानसभा जबलपुर पश्चिम - 2024',
  totalVoters: 'कुल मतदाता',
  FindVoter: 'मतदाता खोजें',
  FindFamily: 'परिवार खोजें',
  Print: 'प्रिंट करें',
  CasteData: 'जातिगत आंकड़ा',
  Vote: 'मतदान',
  Update: 'अपडेट करें',
  NameFatherHusbandSurname: 'नाम/पिता/पति/सरनेम',
  VillageJuryArea: 'ग्राम/पंचायत/क्षेत्र',

  DivisionNumber: 'भाग संख्या',
  Division: 'भाग',

  SaralNumber: 'सरल क्रमांक',
  saralKrimank: 'सं. क्र.',

  search: ' सर्च करें',
  voterInformation: `मतदाता की जानकारी`,
  panchayatKshetra: 'पंचायत/क्षेत्र',
  panchayat: 'पंचायत',
  area: 'क्षेत्र',
  name: 'नाम',
  fatherHusband: 'पिता/पति',
  ageSex: 'उम्र/लिंग',
  caste: 'जाति',
  otherCaste: 'अन्य समाज',
  HouseNumber: 'म.क्र.',
  address: 'पता',
  mobile: 'मोबाइल',
  dob: 'जन्म दिनांक',
  epicNumber: 'ईपिक नंबर',
  priority: 'प्रायोरिटी',
  available: 'उपलब्ध',
  status: 'स्थिति',
  voteCenter: 'मतदान केंद्र',
  selfReceipt: 'स्वयं का पर्ची',
  familyReceipt: 'पूरे परिवार का पर्ची',
  PrimarySchoolBuildingJabalpur: 'प्राथमिक शाला भवन जबलपुर',
};

export default hindiText;
